baseURL = "https://yogiadi.github.io/"
languageCode = "en-us"
title = "Aditya Yogi's Blog"
theme = "PaperMod"

[params]
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowShareButtons = true
  defaultTheme = "auto"
  # homeInfoParams = { Title = "Welcome to My Blog", Content = "Thoughts, insights, and deep dives from a Data Engineer." }

[params.profileMode]
  enabled = true
  title = "Aditya Yogi"
  # subtitle = "Data Engineering | Productivity | Spirituality"
  # imageUrl = "images/profile.jpg"
  # imageTitle = "Profile Photo"
  buttons = [
    { name = "Blog Posts", url = "/posts" },
    { name = "LinkedIn", url = "https://www.linkedin.com/in/aditya-yogi-48337784/" },
    { name = "GitHub", url = "https://github.com/yogiadi" }
  ]

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Posts"
  url = "/posts"
  weight = 2
